name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Kycloak-nodejs-connect test for NodeJS version ${{ matrix.node-version }} on @ ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30   # Just in case something goes realy real realy BAD.....

    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        #node-version: [10.x, 12.x, 14.x, 16.x]
        node-version: [16.x]
        #os: [ubuntu-20.04, windows-2019, macos-10.15] Widnwos dioes not support docker and macos chews through the minutes
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint code 
      run: npm run lint

    - name: Start Keycloak docker container and finish startup processing
      run: |
        make up
        chmod +x ./WaitKeycloakAppRunning.sh
        ./WaitKeycloakAppRunning.sh

    - name: Run test against code
      run: npm run test

    - name: Pacakge code 
      run: npm pack
